// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

interface IERC20 {
    function transfer(address to, uint256 value) external returns (bool);
    function transferFrom(address from, address to, uint256 value) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
}

/**
 * @title PaymentEscrow
 * @notice Escrow contract for Comnetish compute leases paid in USDC.
 * @dev Tenants deposit upfront; oracle settles to provider; cancellation is possible before start window expires.
 */
contract PaymentEscrow {
    /**
     * @notice Lease record tracked by escrow.
     * @param tenant Tenant address paying for compute.
     * @param provider Provider address receiving payment.
     * @param amount Escrowed USDC amount in smallest units.
     * @param createdAt Lease creation timestamp.
     * @param startedAt Lease start timestamp (0 if not started).
     * @param maxDuration Maximum lease duration in seconds.
     * @param isSettled True if funds have been paid out.
     * @param isCancelled True if lease has been cancelled/refunded.
     */
    struct LeaseEscrow {
        address tenant;
        address provider;
        uint256 amount;
        uint64 createdAt;
        uint64 startedAt;
        uint64 maxDuration;
        bool isSettled;
        bool isCancelled;
    }

    /**
     * @notice Emitted when a lease escrow is created.
     */
    event LeaseCreated(
        uint256 indexed leaseId,
        address indexed tenant,
        address indexed provider,
        uint256 amount,
        uint64 maxDuration
    );

    /**
     * @notice Emitted when lease settlement is finalized.
     */
    event LeaseSettled(uint256 indexed leaseId, address indexed settledBy, uint256 amount);

    /**
     * @notice Emitted when lease is cancelled and tenant refunded.
     */
    event LeaseCancelled(uint256 indexed leaseId, address indexed tenant, uint256 refundedAmount);

    /**
     * @notice Emitted when payment is released to provider.
     */
    event PaymentReleased(uint256 indexed leaseId, address indexed provider, uint256 amount);

    /**
     * @notice Address of the USDC token used for escrow.
     */
    IERC20 public immutable usdc;

    /**
     * @notice Oracle/server authorized to mark start and settle leases pre-expiry.
     */
    address public oracle;

    /**
     * @notice Owner with permission to rotate oracle.
     */
    address public owner;

    /**
     * @notice Cancellation window for unstarted leases.
     */
    uint64 public constant CANCEL_WINDOW = 5 minutes;

    mapping(uint256 => LeaseEscrow) public leases;

    error Unauthorized();
    error InvalidAddress();
    error InvalidAmount();
    error LeaseAlreadyExists();
    error LeaseNotFound();
    error LeaseAlreadyFinalized();
    error LeaseAlreadyStarted();
    error CancellationWindowExpired();
    error LeaseNotExpired();
    error TransferFailed();

    /**
     * @notice Creates a new escrow contract.
     * @param usdcToken Address of USDC token contract.
     * @param oracleAddress Address of authorized oracle.
     */
    constructor(address usdcToken, address oracleAddress) {
        if (usdcToken == address(0) || oracleAddress == address(0)) {
            revert InvalidAddress();
        }

        usdc = IERC20(usdcToken);
        oracle = oracleAddress;
        owner = msg.sender;
    }

    modifier onlyOwner() {
        if (msg.sender != owner) revert Unauthorized();
        _;
    }

    modifier onlyOracle() {
        if (msg.sender != oracle) revert Unauthorized();
        _;
    }

    /**
     * @notice Updates oracle address used for settlement authorization.
     * @param newOracle New oracle address.
     */
    function setOracle(address newOracle) external onlyOwner {
        if (newOracle == address(0)) revert InvalidAddress();
        oracle = newOracle;
    }

    /**
     * @notice Creates a lease escrow by transferring tenant USDC into this contract.
     * @param leaseId Unique lease ID generated by off-chain orchestration.
     * @param provider Provider receiving settlement funds.
     * @param amount USDC amount to escrow in smallest units.
     * @param maxDuration Maximum lease duration in seconds.
     */
    function depositForLease(uint256 leaseId, address provider, uint256 amount, uint64 maxDuration) external {
        if (provider == address(0)) revert InvalidAddress();
        if (amount == 0 || maxDuration == 0) revert InvalidAmount();
        if (leases[leaseId].tenant != address(0)) revert LeaseAlreadyExists();

        bool moved = usdc.transferFrom(msg.sender, address(this), amount);
        if (!moved) revert TransferFailed();

        leases[leaseId] = LeaseEscrow({
            tenant: msg.sender,
            provider: provider,
            amount: amount,
            createdAt: uint64(block.timestamp),
            startedAt: 0,
            maxDuration: maxDuration,
            isSettled: false,
            isCancelled: false
        });

        emit LeaseCreated(leaseId, msg.sender, provider, amount, maxDuration);
    }

    /**
     * @notice Marks a lease as started, preventing tenant cancellation.
     * @param leaseId Lease ID to mark started.
     */
    function markLeaseStarted(uint256 leaseId) external onlyOracle {
        LeaseEscrow storage lease = leases[leaseId];
        if (lease.tenant == address(0)) revert LeaseNotFound();
        if (lease.isSettled || lease.isCancelled) revert LeaseAlreadyFinalized();
        if (lease.startedAt != 0) revert LeaseAlreadyStarted();

        lease.startedAt = uint64(block.timestamp);
    }

    /**
     * @notice Settles lease payment to provider.
     * @dev Oracle may settle anytime, otherwise anyone can settle once max duration is exceeded.
     * @param leaseId Lease ID to settle.
     */
    function settleLease(uint256 leaseId) external {
        LeaseEscrow storage lease = leases[leaseId];
        if (lease.tenant == address(0)) revert LeaseNotFound();
        if (lease.isSettled || lease.isCancelled) revert LeaseAlreadyFinalized();

        bool oracleCall = msg.sender == oracle;
        uint256 expiryAnchor = lease.startedAt == 0 ? lease.createdAt : lease.startedAt;

        if (!oracleCall && block.timestamp < expiryAnchor + lease.maxDuration) {
            revert LeaseNotExpired();
        }

        if (lease.startedAt == 0) {
            lease.startedAt = uint64(block.timestamp);
        }

        lease.isSettled = true;

        bool moved = usdc.transfer(lease.provider, lease.amount);
        if (!moved) revert TransferFailed();

        emit PaymentReleased(leaseId, lease.provider, lease.amount);
        emit LeaseSettled(leaseId, msg.sender, lease.amount);
    }

    /**
     * @notice Cancels an unstarted lease and refunds tenant if within cancellation window.
     * @param leaseId Lease ID to cancel.
     */
    function cancelLease(uint256 leaseId) external {
        LeaseEscrow storage lease = leases[leaseId];
        if (lease.tenant == address(0)) revert LeaseNotFound();
        if (lease.isSettled || lease.isCancelled) revert LeaseAlreadyFinalized();
        if (msg.sender != lease.tenant) revert Unauthorized();
        if (lease.startedAt != 0) revert LeaseAlreadyStarted();
        if (block.timestamp > lease.createdAt + CANCEL_WINDOW) revert CancellationWindowExpired();

        lease.isCancelled = true;

        bool moved = usdc.transfer(lease.tenant, lease.amount);
        if (!moved) revert TransferFailed();

        emit LeaseCancelled(leaseId, lease.tenant, lease.amount);
    }
}
